name: Run PowerShell Script

on:
    push:
                branches: [ main ]
    pull_request:
                branches: [ main ]

jobs:
        run-script:
                strategy:
                        matrix:
                                os: [ubuntu-latest, windows-latest]
                runs-on: ${{ matrix.os }}
                timeout-minutes: 20
              
                steps:
                -   name: Checkout code
                    uses: actions/checkout@v4
    
                -   name: Set up Docker
                    if: runner.os == 'Windows'
                    run: |
                        sudo apt-get update
                        sudo apt-get install -y docker.io
                        sudo systemctl start docker
        
                -   name: Install Make (Windows)
                    if: runner.os == 'Windows'
                    run: choco install make -y
        
                -   name: Build image and run test
                    run: make build-and-run-job
                    timeout-minutes: 10
