name: Run PowerShell Script

on:
    push:
                branches: [ main ]
    pull_request:
                branches: [ main ]

jobs:
        run-script:
                strategy:
                        matrix:
                                os: [ubuntu-latest, windows-latest]
                runs-on: ${{ matrix.os }}
                timeout-minutes: 20
              
                steps:
                -   name: Checkout code
                    uses: actions/checkout@v4
    
                -   name: Set up Docker
                    if: runner.os == 'Windows'
                    shell: powershell
                    run: |
                          wsl --install -d Ubuntu -y

                          Start-Sleep -Seconds 30
                          wsl -d Ubuntu -e bash -c "
                          sudo apt update && sudo apt upgrade -y
                          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
                          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
                          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                          sudo apt update
                          sudo apt install -y docker-ce docker-ce-cli containerd.io
                          sudo usermod -aG docker \$USER
                          sudo service docker start"
                -   name: Install Make (Windows)
                    if: runner.os == 'Windows'
                    run: choco install make -y
        
                -   name: Build image and run test
                    run: make build-and-run-job
                    timeout-minutes: 10
