name: Run PowerShell Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Makefile
        run: make install
      
  run-script:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Makefile
        run: make test-script
