name: Run PowerShell Script

on:
    push:
                branches: [ main ]
    pull_request:
                branches: [ main ]

jobs:
        run-test-ubuntu:
                runs-on: ubuntu-latest
                timeout-minutes: 20
              
                steps:
                -   name: Checkout code
                    uses: actions/checkout@v4
                    
                -   name: Build image and run test
                    run: make build-image-and-run-container
                    timeout-minutes: 10
                    
        run-test-windows:
                runs-on: windows-latest
                timeout-minutes: 20
              
                steps:
                -   name: Checkout code
                    uses: actions/checkout@v4
                -   name: Install Make for Windows
                    run: |
                        Set-ExecutionPolicy Bypass -Scope Process -Force
                        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
                        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
                        choco install make
                        choco install 7zip.install -y

                -   name: Intall modules for tests
                    run: make install-modules
                    timeout-minutes: 10
                    
                -   name: Run tests
                    run: make run-pester-tests
                    timeout-minutes: 10
